name: Reusable deploy workflow
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.perform_deploy == 'true' }}
    steps:
      - name: Deploy build to target
        run: |
          echo build_id: ${{ github.event.inputs.build_id }} deploy_target: ${{ github.event.inputs.deploy_target }}
