name: Reusable deploy workflow
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        run: |
          echo build_id: ${{ inputs.build_id }} deploy_target: ${{ inputs.deploy_target }}
