name: learn-github-actions
on: [push]
env:
  qa: toJSON({"bucket":"qa-bucket", "distID":"qa-dist-id"})
  prod: fromJSON({"bucket":"prod-bucket", "distID":"prod-dist-id"})
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: |
          echo "The current bucket is: ${{env.qa.bucket}}"
          echo "The current distID is: ${{env.prod.distID}}"
          echo "The current biba is: ${{env.qa}}"
